### ISSUE TITLE
Durazno- Nte Abbreviation Bug

### ISSUE THREAD

**Issue by s-regan** [KaartGroup/KaartValidator#33]
Street names that have any word that ends in 'nte' followed by another word will be caught by accident. Example: Calle Vicente Guerrero and Calle Vicente Guerrero Sur will be caught, but Calle Vicente will not.

**Comment by Rdclare75** [comment]
@s-regan  I can't seem to replicate this bug, so i have not found a way to fix this. If you run into it again please slack me the osm object id. It is also possible that it's not the name that contains the abbreviation but it's alt_name.

**Comment by s-regan** [comment]
I believe the cause of this is an outdated version of the validator. The people who are affected by this are using a .mapcss file stored locally. Thanks for checking! I'm closing the issue. If anything else comes up I can slack you.
