### ISSUE TITLE
Durazno/Mexico/Sanitas: Oneway = any value that is not yes 

### ISSUE THREAD

**Issue by s-regan** [KaartGroup/KaartValidator#34]
Sanitas would like the validator to check for oneways labeled with anything that is not yes or no. Ex. oneway = Calle Benito, oneway = #/$/any special character should throw an error in the results pane.

**Comment by Rdclare75** [comment]
@s-regan Hey I added a check for this, if its not what you are wanting please let me know.

**Comment by s-regan** [comment]
Yup, that's exactly what we're looking for. Thanks! I'll close the issue.
