### ISSUE TITLE
Double Prefix Update 

### ISSUE THREAD

**Issue by s-regan** [KaartGroup/KaartValidator#35]
Sanitas would like the following in regard to double prefixes:
Throw an error when:
1. The first of double prefixes is "Calle" (Calle Calle Hidalgo, Calle Privada Hidalgo)
2. The first of double prefixes is the same as the second (Avenida Avenida Hidalgo, Privada Privada Hidalgo)
Do not throw an error when:
1. A double prefix is provided as a name (Calle Calle, Avenida Circuito, Privada Prolongación)
2. Multiple prefixes are separated by another word, even if they are the same prefix (Privada Primera Privada De Manuel Doblado, Avenida Primera Privada De Manuel Doblado)
3. There is a name with double prefixes and does not begin with "Calle"  (Prolongación Avenida Central, Boulevard Camino Real)

**Comment by taylorsmock** [comment]
So 1 and 2 are desired errors, and 3, 4, and 5 are all desired warnings? Or do they not want 3, 4, and 5 removed altogether?

**Comment by s-regan** [comment]
3, 4, and 5 are to be discussed at the QA meeting and with Sanitas's team lead. Your question sparked some interesting discussion. They did, however, come to the consensus that of there are 3 or more prefixes, that should throw a warning. I'll update this when the team lead returns.

**Comment by Rdclare75** [comment]
@s-regan i have made changes that follows the rules as stated above, you said this would be discussed in a QA meeting so before i push is there anything else that needs to be excluded or added?

**Comment by s-regan** [comment]
@Rdclare75 Sounds like we're good for now. Thank you very much
